### ISSUE TITLE
Bearbeitet/Richtig Algorithmus

### ISSUE THREAD

**Issue by jmne** [jancodet/Quizzer#3]
Wir brauchen noch nen Alg. der entscheidet ob eine Frage genommen/geskipt werden soll, aufgrund der Anzahl an Bearbeitungen..
![screenshot_1](https://user-images.githubusercontent.com/14363947/52788892-a7b38880-3062-11e9-874a-b772f2663042.png)

**Comment by KingKevin23** [comment]
Kümmere mich morgen drum
